### ISSUE TITLE
Error when connecting to the sql server

### ISSUE THREAD

**Issue by wpzag** [Namoshek/docker-php-mssql#1]
I get this error when i try to connect to the sql  server. im using namoshek/php-mssql:7.4-fpm .
```
SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.9.so.1.1' : file not foundnot
```

**Comment by Namoshek** [comment]
I cannot reproduce the issue. Are you sure you are running your application in the container and not on the host?

To reproduce, I tested `namoshek/php-mssql:7.4-fpm`, `namoshek/php-mssql:8.1-cli` and `namoshek/php-mssql:8.1-cli-alpine` with the following setup using the commands:
```sh
docker-compose up -d
docker exec -it php /bin/bash
php connect_sqlsrv.php
```

docker-compose.yml
```yaml
version: '3.8'

services:
  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlsrv
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S0m3th1ng_S3cur3
  
  php:
    image: namoshek/php-mssql:7.4-fpm
    container_name: php
    command: ['/bin/bash']
    restart: unless-stopped
    stop_signal: SIGKILL
    working_dir: /app
    tty: true
    depends_on:
      - sqlsrv
    volumes:
      - ./connect_sqlsrv.php:/app/connect_sqlsrv.php
    environment:
      - "MSSQL_HOST=sqlsrv"
      - "MSSQL_PORT=1433"
      - "MSSQL_USERNAME=sa"
      - "MSSQL_PASSWORD=S0m3th1ng_S3cur3"
      - "MSSQL_DATABASE=master"
```

connect_sqlsrv.php
```php
<?php

function test_sqlsrv_connection()
{
    $host = getenv('MSSQL_HOST');
    $port = getenv('MSSQL_PORT');

    $connection = sqlsrv_connect("${host},${port}", [
        'UID' => getenv('MSSQL_USERNAME'),
        'PWD' => getenv('MSSQL_PASSWORD'),
        'Database' => getenv('MSSQL_DATABASE'),
    ]);

    if ($connection === false) {
        return 'failed';
    }

    $success = sqlsrv_query($connection, 'SELECT 1');

    if ($success === false) {
        return 'failed';
    }

    return 'success';
}

function test_pdo_sqlsrv_connection()
{
    $host = getenv('MSSQL_HOST');
    $port = getenv('MSSQL_PORT');
    $database = getenv('MSSQL_DATABASE');
    $username = getenv('MSSQL_USERNAME');
    $password = getenv('MSSQL_PASSWORD');

    try {
        $connection = new PDO("sqlsrv:server=${host},${port};Database=${database};ConnectionPooling=0", $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        $success = $connection->query('SELECT 1');

        if ($success === false) {
            return 'failed';
        }

        return 'success';
    } catch (PDOException $e) {
        return 'failed';
    }
}

echo '== PHP extensions ==' . PHP_EOL;
echo 'sqlsrv version: ' . phpversion('sqlsrv') . PHP_EOL;
echo 'pdo_sqlsrv version: ' . phpversion('pdo_sqlsrv') . PHP_EOL;
echo PHP_EOL;

echo '== Environment variables ==' . PHP_EOL;
echo 'MSSQL_HOST: ' . getenv('MSSQL_HOST') . PHP_EOL;
echo 'MSSQL_PORT:' . getenv('MSSQL_PORT') . PHP_EOL;
echo 'MSSQL_USERNAME:' . getenv('MSSQL_USERNAME') . PHP_EOL;
echo 'MSSQL_PASSWORD:' . getenv('MSSQL_PASSWORD') . PHP_EOL;
echo 'MSSQL_DATABASE:' . getenv('MSSQL_DATABASE') . PHP_EOL;
echo PHP_EOL;

echo 'Connecting to SQL Server using `sqlsrv` extension... ' . test_sqlsrv_connection() . PHP_EOL;
echo 'Connecting to SQL Server using `pdo_sqlsrv` extension... ' . test_pdo_sqlsrv_connection() . PHP_EOL;
```

---

Results from `namoshek/php-mssql:7.4-fpm`:
```
== PHP extensions ==
sqlsrv version: 5.10.0
pdo_sqlsrv version: 5.10.0

== Environment variables ==
MSSQL_HOST: sqlsrv
MSSQL_PORT:1433
MSSQL_USERNAME:sa
MSSQL_PASSWORD:S0m3th1ng_S3cur3
MSSQL_DATABASE:master

Connecting to SQL Server using `sqlsrv` extension... success
Connecting to SQL Server using `pdo_sqlsrv` extension... success
```
