### ISSUE TITLE
Not sure how to to link apache to this

### ISSUE THREAD

**Issue by otaku-soft** [Namoshek/docker-php-mssql#9]
I used this as my docker-compose.  Problem is after .php files are still being processed as regular text.  I tried some tips online but none were useful in helping.  Is there an image with apache and this already pre-installed or steps to get it working.  Thanks.  
```
version: '3.8'
services:
    php-apache-environment:
        container_name: gunzsite
        image: namoshek/php-mssql:8.0-fpm
        volumes:
            - ./www:/var/www
        ports:
            - 8100:80
```

**Comment by Namoshek** [comment]
There is no Apache image variant provided by this repository until now. I haven't tried it, but you should be able to simply take the [`8.2/fpm/Dockerfile`](https://github.com/Namoshek/docker-php-mssql/blob/6d589322ddb49ca335135ce194d2c69ec378d679/8.2/fpm/Dockerfile) and replace the base image on the first line with `php:8.2-apache-bullseye`. You would then also need to change the config in your `docker-compose.yml` to use your custom Dockerfile instead:
```yaml
version: '3.8'
services:
  php-apache-environment:
    container_name: gunzsite
    image: php-8.2-apache-bullseye-sqlsrv:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
    ports:
      - 8100:80
```
Assuming that your `docker-compose.yml` and `Dockerfile` are inside the same folder.
